# Generated by Django 4.2.1 on 2023-06-01 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdateMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=150, null=True)),
                ('last_update', models.DateTimeField(blank=True, help_text='Last time model data was updated', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalitiesNatCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natcode', models.CharField(max_length=11)),
                ('nameunit', models.CharField(max_length=100)),
                ('nuts_2_code', models.CharField(max_length=4)),
                ('nuts_3_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='NutsEurope',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('nuts_id', models.CharField(blank=True, max_length=5, null=True)),
                ('levl_code', models.SmallIntegerField(blank=True, null=True)),
                ('cntr_code', models.CharField(blank=True, max_length=2, null=True)),
                ('name_latn', models.CharField(blank=True, max_length=70, null=True)),
                ('nuts_name', models.CharField(blank=True, max_length=106, null=True)),
                ('mount_type', models.SmallIntegerField(blank=True, null=True)),
                ('urbn_type', models.SmallIntegerField(blank=True, null=True)),
                ('coast_type', models.SmallIntegerField(blank=True, null=True)),
                ('fid', models.CharField(blank=True, max_length=5, null=True)),
                ('europecountry_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nuts_europe',
            },
        ),
        migrations.CreateModel(
            name='ObservationBarChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('month', models.IntegerField()),
                ('category', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('ccaa_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'observationbardata',
            },
        ),
        migrations.CreateModel(
            name='ObservationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccaa', models.CharField(max_length=150, null=True)),
                ('ccaa_code', models.CharField(max_length=10, null=True)),
                ('provincia', models.CharField(max_length=150)),
                ('municipi', models.CharField(max_length=150)),
                ('n_bite', models.IntegerField()),
                ('n_albo', models.IntegerField()),
                ('n_aegypti', models.IntegerField()),
                ('n_culex', models.IntegerField()),
                ('n_japonicus', models.IntegerField(null=True)),
                ('n_koreicus', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('trampeo_albo', models.BooleanField(blank=True, null=True)),
                ('ma_albo', models.BooleanField(blank=True, null=True)),
                ('municipi_code', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'observationdata',
            },
        ),
        migrations.CreateModel(
            name='ParticipationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccaa_name', models.CharField(max_length=150)),
                ('n', models.IntegerField()),
                ('category', models.CharField(max_length=150)),
                ('year', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'participationdata',
            },
        ),
        migrations.CreateModel(
            name='RuntimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SpeedMeterData',
            fields=[
                ('version_UUID', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField()),
                ('nuts_2', models.CharField(blank=True, max_length=4, null=True)),
            ],
            options={
                'verbose_name': 'speedmeterdata',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_by_nuts', to='main.nutseurope')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NatCodePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trampeo', models.BooleanField()),
                ('ma', models.BooleanField()),
                ('mosquito_class', models.CharField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('natmunicipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.municipalitiesnatcode')),
            ],
        ),
    ]
