# Generated by Django 4.2.1 on 2023-05-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=150)),
                ('municipi', models.CharField(max_length=150)),
                ('n_bite', models.IntegerField()),
                ('n_albo', models.IntegerField()),
                ('n_aegypti', models.IntegerField()),
                ('n_culex', models.IntegerField()),
            ],
        ),
    ]
