# Generated by Django 4.2.1 on 2023-06-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_municipalitiesnatcode_lau_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipalitiesnatcode',
            name='lau_id',
        ),
        migrations.AddField(
            model_name='municipalitiesnatcode',
            name='gisco_id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
