# Generated by Django 4.2.1 on 2023-05-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_observationdata_ccaa_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationdata',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
