# Generated by Django 4.2.1 on 2023-05-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_observationdata_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationdata',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
