# Generated by Django 4.2.1 on 2023-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_nutseurope_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdateMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=150, null=True)),
                ('last_update', models.DateTimeField(blank=True, help_text='Last time model data was updated', null=True)),
            ],
        ),
    ]
