# Generated by Django 4.2.1 on 2023-05-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_observationbarchartdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalitiesNatCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natcode', models.CharField(max_length=11)),
                ('nameunit', models.CharField(max_length=30)),
                ('nuts_2_code', models.CharField(max_length=4)),
                ('nuts_3_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name='observationbarchartdata',
            options={'verbose_name': 'observationbardata'},
        ),
    ]
