# Generated by Django 4.2.1 on 2023-05-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_natcodepresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='natcodepresence',
            name='mosquito_class',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='observationdata',
            name='ma_albo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observationdata',
            name='n_japonicus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='observationdata',
            name='n_koreicus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='observationdata',
            name='trampeo_albo',
            field=models.BooleanField(default=False),
        ),
    ]
