# Generated by Django 4.2.1 on 2023-05-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_natcodepresence_mosquito_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationdata',
            name='municipi_code',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
