# Generated by Django 4.2.1 on 2023-05-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_observationdata_ma_albo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalitiesnatcode',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
