# Generated by Django 4.2.1 on 2023-05-31 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_municipalitiesnatcode_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipalitiesnatcode',
            name='year',
        ),
        migrations.AddField(
            model_name='natcodepresence',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
