# Generated by Django 4.2.1 on 2023-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_speedmeterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='speedmeterdata',
            options={'verbose_name': 'speedmeterdata'},
        ),
    ]
