# Generated by Django 4.2.1 on 2023-06-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_runtimesettings_alter_speedmeterdata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutseurope',
            options={},
        ),
    ]
